---
- name: Update dotfiles
  git:
    repo: https://github.com/senyoltw/dotfiles
    dest: ~/dotfiles
    update: yes
    force: yes
    track_submodules: yes

# git updateした最新のplaybookを実行するため分割
- name: Install dotfiles
  include_tasks: ~/dotfiles/osx/install_dotfiles.yml

