---
# zinitがインストール済みか確認
- name: Check dotfiles zinit
  stat:
    path: ~/dotfiles/.zinit/bin/zinit.zsh
  register: dotfiles_zinit

# dotfilesのInstall
# 更新はdotfiles側でやりたいので最初だけしかしない
- name: Install dotfiles
  git:
    repo: https://github.com/senyoltw/dotfiles
    dest: ~/dotfiles
    track_submodules: yes
  when: not dotfiles_zinit.stat.exists

# シンボリックリンクを張るファイル/フォルダは明示的に宣言
- name: Link dotfiles
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
  with_items:
    - .zshrc
    - .zinit

# for zsh compinit err fix
# err msg -> zsh compinit: insecure directories, run compaudit for list.
# Ignore insecure directories and continue [y] or abort compinit [n]?
- name: for zsh compinit err fix
  file:
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /usr/local/share/zsh/site-functions
    - /usr/local/share/zsh
