---
- name: Update dotfiles
  git:
    repo: https://github.com/senyoltw/dotfiles
    dest: ~/dotfiles
    update: yes
    track_submodules: yes

- name: Link dotfiles
  file:
    src: ~/dotfiles/"{{ item }}"
    dest: ~/"{{ item }}"
    state: link
    with_items:
      - .zshrc
      - .zinit