---
# dotfilesのInstall
- name: Install or Update dotfiles
  git:
    repo: https://github.com/senyoltw/dotfiles
    dest: ~/dotfiles
    update: yes
    track_submodules: yes

# シンボリックリンクを張るファイル/フォルダは明示的に宣言
- name: Link dotfiles
  file:
    src: ~/dotfiles/{{ item }}
    dest: ~/{{ item }}
    state: link
  with_items:
    - .zshrc

# for zsh compinit err fix
# err msg -> zsh compinit: insecure directories, run compaudit for list.
# Ignore insecure directories and continue [y] or abort compinit [n]?
# - name: for zsh compinit err fix
#  file:
#    path: "{{ item }}"
#    mode: 0755
#  with_items:
#    - /usr/local/share/zsh/site-functions
#    - /usr/local/share/zsh
